spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_servico
    username: root
    password: banco123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true   
  
